# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TypesUrl(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, autogenerated: bool=None, code: int=None, key: str=None, url: str=None):  # noqa: E501
        """TypesUrl - a model defined in Swagger

        :param autogenerated: The autogenerated of this TypesUrl.  # noqa: E501
        :type autogenerated: bool
        :param code: The code of this TypesUrl.  # noqa: E501
        :type code: int
        :param key: The key of this TypesUrl.  # noqa: E501
        :type key: str
        :param url: The url of this TypesUrl.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'autogenerated': bool,
            'code': int,
            'key': str,
            'url': str
        }

        self.attribute_map = {
            'autogenerated': 'autogenerated',
            'code': 'code',
            'key': 'key',
            'url': 'url'
        }

        self._autogenerated = autogenerated
        self._code = code
        self._key = key
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'TypesUrl':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The types.Url of this TypesUrl.  # noqa: E501
        :rtype: TypesUrl
        """
        return util.deserialize_model(dikt, cls)

    @property
    def autogenerated(self) -> bool:
        """Gets the autogenerated of this TypesUrl.


        :return: The autogenerated of this TypesUrl.
        :rtype: bool
        """
        return self._autogenerated

    @autogenerated.setter
    def autogenerated(self, autogenerated: bool):
        """Sets the autogenerated of this TypesUrl.


        :param autogenerated: The autogenerated of this TypesUrl.
        :type autogenerated: bool
        """

        self._autogenerated = autogenerated

    @property
    def code(self) -> int:
        """Gets the code of this TypesUrl.


        :return: The code of this TypesUrl.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this TypesUrl.


        :param code: The code of this TypesUrl.
        :type code: int
        """

        self._code = code

    @property
    def key(self) -> str:
        """Gets the key of this TypesUrl.


        :return: The key of this TypesUrl.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this TypesUrl.


        :param key: The key of this TypesUrl.
        :type key: str
        """

        self._key = key

    @property
    def url(self) -> str:
        """Gets the url of this TypesUrl.


        :return: The url of this TypesUrl.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this TypesUrl.


        :param url: The url of this TypesUrl.
        :type url: str
        """

        self._url = url
