---
swagger: "2.0"
info:
  description: "Swagger API for Golang Project Goshort."
  version: "1.0"
  title: "Goshort Swagger API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Nikolay Vasilev"
    email: "nikhovas@yandex.ru"
  license:
    name: "MIT"
    url: "https://github.com/nikhovas/goshort/blob/master/LICENSE"
basePath: "/api/"
paths:
  /{key}:
    get:
      summary: "Get redirection page"
      operationId: "redirect"
      produces:
      - "text/html"
      parameters:
      - name: "key"
        in: "path"
        description: "Url key"
        required: true
        type: "string"
      responses:
        "301":
          description: "If temporary redirect"
        "308":
          description: "If permanent redirect"
        "404":
          description: "No such url"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /urls/:
    post:
      tags:
      - "Url"
      summary: "Create url by sent data"
      description: "Use json to generate url. If you want to create autogenerated\
        \ key, leave key field empty."
      operationId: "post_url"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "url"
        description: "This is body string param"
        required: true
        schema:
          $ref: "#/definitions/types.Url"
      responses:
        "201":
          description: "Successfully created"
          schema:
            $ref: "#/definitions/types.Url"
        "400":
          description: "Bad input data"
        "409":
          description: "Already exists"
      x-swagger-router-controller: "swagger_server.controllers.url_controller"
  /urls/{key}:
    get:
      tags:
      - "Url"
      summary: "Get url by key"
      operationId: "get_url"
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        description: "Url key"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/types.Url"
        "400":
          description: "Bad input data"
        "404":
          description: "No such url"
      x-swagger-router-controller: "swagger_server.controllers.url_controller"
    delete:
      tags:
      - "Url"
      summary: "Delete url by key"
      operationId: "delete_url"
      parameters:
      - name: "key"
        in: "path"
        description: "Url key"
        required: true
        type: "string"
      responses:
        "204":
          description: "Successfully deleted"
        "400":
          description: "Bad input data"
        "404":
          description: "No such url"
      x-swagger-router-controller: "swagger_server.controllers.url_controller"
    patch:
      tags:
      - "Url"
      summary: "Edit url by sent data"
      operationId: "patch_url"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "path"
        description: "Url key"
        required: true
        type: "string"
      - in: "body"
        name: "url"
        description: "This is body string param"
        required: true
        schema:
          $ref: "#/definitions/types.Url"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/types.Url"
        "400":
          description: "Bad input data"
        "404":
          description: "No such url"
      x-swagger-router-controller: "swagger_server.controllers.url_controller"
definitions:
  types.Url:
    type: "object"
    properties:
      autogenerated:
        type: "boolean"
        example: false
      code:
        type: "integer"
        example: 301
      key:
        type: "string"
        example: "example"
      url:
        type: "string"
        example: "example.com"
    example:
      code: 301
      autogenerated: false
      key: "example"
      url: "example.com"
