import connexion
import six

from swagger_server.models.types_url import TypesUrl  # noqa: E501
from swagger_server import util


def delete_url(key):  # noqa: E501
    """Delete url by key

     # noqa: E501

    :param key: Url key
    :type key: str

    :rtype: None
    """

    return '', 204


def get_url(key):  # noqa: E501
    """Get url by key

     # noqa: E501

    :param key: Url key
    :type key: str

    :rtype: TypesUrl
    """

    if key == 'demo':
        return TypesUrl(False, 301, 'demo', 'example.com')
    else:
        return '', 404


def patch_url(key, url):  # noqa: E501
    """Edit url by sent data

     # noqa: E501

    :param key: Url key
    :type key: str
    :param url: This is body string param
    :type url: dict | bytes

    :rtype: TypesUrl
    """
    if connexion.request.is_json:
        url = TypesUrl.from_dict(connexion.request.get_json())  # noqa: E501

    return url, 200


def post_url(url):  # noqa: E501
    """Create url by sent data

    Use json to generate url. If you want to create autogenerated key, leave key field empty. # noqa: E501

    :param url: This is body string param
    :type url: dict | bytes

    :rtype: TypesUrl
    """
    if connexion.request.is_json:
        url = TypesUrl.from_dict(connexion.request.get_json())  # noqa: E501
    return url, 201
